"use client"
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "@/lib/registry";
import GlobalStyles from "@/styles/GlobalStyle";
import { CartContextProvider } from "@/components/CartContext";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
        <StyledComponentsRegistry>
          <GlobalStyles/>
        {children}
        </StyledComponentsRegistry>
        </CartContextProvider>
      </body>
    </html>
  );
}
